# Change these first
owner: xaif # Your GitHub username
repo: upptime # Your GitHub repository name
assignees:
  - xaif

# Add your sites here
sites:
  - name: Website
    url: https://momentum.studio
  - name: Client Area
    url: https://clients.momentum.studio
  - name: Shared Hosting
    url: https://cpanel.momentum.studio

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: status.momentum.studio
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /status
  logoUrl: https://momentum.studio/wp-content/uploads/2017/05/ms-logo-no-margin.png
  name: Momentum Studio Status
  introTitle: See how our services are performing
  introMessage: This status page shows how our services are performing live. We do also add messages to this site from time to time to explain downtimes.
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://momentum.studio

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
